name: Create a Build and add it to the S3 bucket

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: [published]

env:
  S3_BUCKET_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install all the dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to S3 Bucket
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{secrets.S3_BUCKET}}
          bucket-region: ${{env.S3_BUCKET_REGION}}
